/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class PrototypeAudioProcessorEditor : public AudioProcessorEditor,
									  private Slider::Listener,
									//  private ToggleButton::Listener,
									  private Timer
{
public:
    PrototypeAudioProcessorEditor (PrototypeAudioProcessor&);
    ~PrototypeAudioProcessorEditor();

    //==============================================================================
	void timerCallback() override;
	void paint(Graphics&) override;
	void resized() override;
	void sliderValueChanged(Slider *slider) override;
	void sliderDragStarted(Slider*) override;
	void sliderDragEnded(Slider*) override;

private:
	/*
	// This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    PrototypeAudioProcessor& processor;
	*/
	Slider inputGainSlider;
	Label inputGainLabel;

	Slider outputGainSlider;
	Label outputGainLabel;

	ToggleButton bypassButton;

	//==============================================================================
	PrototypeAudioProcessor& getProcessor() const
	{
		return static_cast<PrototypeAudioProcessor&> (processor);
	}

	AudioProcessorParameter* getParameterFromSlider(const Slider*) const;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (PrototypeAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
