/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SubHarmonicsAudioProcessorEditor : public AudioProcessorEditor,
									  private Slider::Listener,
									  private Button::Listener,
									  private Timer
{
public:
	SubHarmonicsAudioProcessorEditor(SubHarmonicsAudioProcessor&);
	~SubHarmonicsAudioProcessorEditor();

    //==============================================================================
	void timerCallback() override;
	void paint(Graphics&) override;
	void resized() override;
	void sliderValueChanged(Slider *slider) override;
	void sliderDragStarted(Slider*) override;
	void sliderDragEnded(Slider*) override;
	void buttonClicked(Button* button) override;

private:
	/*
	// This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    // SubHarmonicsAudioProcessor& processor;
	*/
	ToggleButton masterBypassButton;
	ToggleButton soloSubButton;
	ToggleButton switchFilterButton;
	ToggleButton harmonicCompensButton;
	ToggleButton muteSubButton;

	Slider inputGainSlider;
	Label inputGainLabel;

	Slider preSubGainSlider;
	Label preSubGainLabel;

	Slider bpFreqSlider;
	Label bpFreqLabel;

	Slider bpQSlider;
	Label bpQLabel;

	Slider hpfFreqSlider;
	Label hpfFreqLabel;

	Slider lpfFreqSlider;
	Label lpfFreqLabel;

	Slider decaySlider;
	Label decayLabel;

	Slider hystSlider;
	Label hystLabel;

	Slider colourSlider;
	Label colourLabel;

	Slider postSubGainSlider;
	Label postSubGainLabel;

	Slider directGainSlider;
	Label directGainLabel;

	Slider outputGainSlider;
	Label outputGainLabel;

	//==============================================================================
	SubHarmonicsAudioProcessor& getProcessor() const
	{
		return static_cast<SubHarmonicsAudioProcessor&> (processor);
	}

	AudioProcessorParameter* getParameterFromSlider(const Slider*) const;
	AudioProcessorParameter* getParameterFromButton(const Button*) const;

	JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(SubHarmonicsAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
