/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
PrototypeAudioProcessorEditor::PrototypeAudioProcessorEditor(PrototypeAudioProcessor& owningProcessor)
	: AudioProcessorEditor(owningProcessor) {

    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (650, 310);

	int defaultTextBoxHeight = 35;	// Text box height in pixels

	// Set properties for Master Bypass Button
	masterBypassButton.addListener(this);
	masterBypassButton.setButtonText("Master Bypass");

	// Set properties for Solo Sub Button
	soloSubButton.addListener(this);
	soloSubButton.setButtonText("Solo Sub");

	// Set properties for the Input Gain Slider
	inputGainSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	inputGainSlider.setRange(0.0, 1.0, 0.01);
	inputGainSlider.setSliderSnapsToMousePosition(false);
	inputGainSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	inputGainSlider.setTextValueSuffix(" Volume");
	inputGainSlider.addListener(this);
	// Set properties for the Input Gain Label
	inputGainLabel.setText("Input Volume", NotificationType::dontSendNotification);

	// Set properties for the Output Gain Slider
	outputGainSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	outputGainSlider.setRange(0.0, 1.0, 0.01);
	outputGainSlider.setSliderSnapsToMousePosition(false);
	outputGainSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	outputGainSlider.setTextValueSuffix(" Volume");
	outputGainSlider.addListener(this);
	// Set properties for the Output Gain Label
	outputGainLabel.setText("Output Volume", NotificationType::dontSendNotification);

	// Set properties for the Pre Sub Gain Slider
	subPreGainSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	subPreGainSlider.setRange(0.0, 1.0, 0.01);
	subPreGainSlider.setSliderSnapsToMousePosition(false);
	subPreGainSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	subPreGainSlider.setTextValueSuffix(" Volume");
	subPreGainSlider.addListener(this);
	// Set properties for the Pre Sub Gain Label
	subPreGainLabel.setText("Sub Pre Gain", NotificationType::dontSendNotification);

	// Set properties for the BP Frequncy Slider
	bpFreqSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	bpFreqSlider.setRange(40, 1000, 1);
	bpFreqSlider.setSliderSnapsToMousePosition(false);
	bpFreqSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	bpFreqSlider.setTextValueSuffix(" Hz");
	bpFreqSlider.setSkewFactor(0.5);
	bpFreqSlider.addListener(this);
	// Set properties for the HPF Frequncy Label
	bpFreqLabel.setText("BP Frequency", NotificationType::dontSendNotification);

	// Set properties for the BP Q Slider
	bpQSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	bpQSlider.setRange(0.5f, 1.f, 0.001f);
	bpQSlider.setSliderSnapsToMousePosition(false);
	bpQSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	//bpQSlider.setSkewFactor(0.5);
	bpQSlider.addListener(this);
	// Set properties for the LPF Frequncy Label
	bpQLabel.setText("BP Q", NotificationType::dontSendNotification);

	// Set properties for the Hysteresis Slider
	hystSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	hystSlider.setRange(0, .1f, .001f);
	hystSlider.setSliderSnapsToMousePosition(false);
	hystSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	hystSlider.addListener(this);
	// Set properties for the Hysteresis Label
	hystLabel.setText("Hysteresis", NotificationType::dontSendNotification);

	// Set properties for the Colour Slider
	colourSlider.setSliderStyle(Slider::RotaryHorizontalVerticalDrag);
	colourSlider.setRange(100.f, 600.f, 1.f);
	colourSlider.setSliderSnapsToMousePosition(false);
	colourSlider.setTextBoxStyle(Slider::TextBoxBelow, false, 50, defaultTextBoxHeight);
	colourSlider.setTextValueSuffix(" Hz");
	colourSlider.setSkewFactor(0.5);
	colourSlider.addListener(this);
	// Set properties for the Colour Label
	colourLabel.setText("Colour", NotificationType::dontSendNotification);

	addAndMakeVisible(&masterBypassButton);
	addAndMakeVisible(&soloSubButton);
	addAndMakeVisible(&inputGainSlider);
	addAndMakeVisible(&inputGainLabel);
	addAndMakeVisible(&outputGainSlider);
	addAndMakeVisible(&outputGainLabel);
	addAndMakeVisible(&subPreGainSlider);
	addAndMakeVisible(&subPreGainLabel);
	addAndMakeVisible(&bpFreqSlider);
	addAndMakeVisible(&bpFreqLabel);
	addAndMakeVisible(&bpQSlider);
	addAndMakeVisible(&bpQLabel);
	addAndMakeVisible(&hystSlider);
	addAndMakeVisible(&hystLabel);
	addAndMakeVisible(&colourSlider);
	addAndMakeVisible(&colourLabel);

	startTimer(50);
}

PrototypeAudioProcessorEditor::~PrototypeAudioProcessorEditor() {
}

//==============================================================================
void PrototypeAudioProcessorEditor::paint (Graphics& g)
{
	// Fill the whole window white
	g.fillAll (Colours::grey);

	// Set the current drawing colour to black
	g.setColour (Colours::black);

	// Set the font size and draw text to the screen
	g.setFont (15.0f);
}

void PrototypeAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..

	int defaultKnobHeight = 80;	// knob height in pixels
	int defaultKnobWidth = 50;	// knob width in pixels

	// Setting button sizes
	masterBypassButton.setBounds(100, 250, 100, 40);
	soloSubButton.setBounds(430, 250, 100, 40);
	
	// Setting slider sizes
	inputGainSlider.setBounds(50, 110, defaultKnobWidth, defaultKnobHeight);
	subPreGainSlider.setBounds(150, 110, defaultKnobWidth, defaultKnobHeight);
	bpFreqSlider.setBounds(250, 165, defaultKnobWidth, defaultKnobHeight);
	bpQSlider.setBounds(250, 55, defaultKnobWidth, defaultKnobHeight);
	hystSlider.setBounds(350, 110, defaultKnobWidth, defaultKnobHeight);
	colourSlider.setBounds(450, 110, defaultKnobWidth, defaultKnobHeight);
	outputGainSlider.setBounds(550, 110, defaultKnobWidth, defaultKnobHeight);
	
	// Setting label sizes
	inputGainLabel.setBounds(35, 90, 80, 15);
	subPreGainLabel.setBounds(135, 90, 80, 15);
	bpFreqLabel.setBounds(235, 145, 80, 15);
	bpQLabel.setBounds(235, 35, 80, 15);
	hystLabel.setBounds(335, 90, 80, 15);
	colourLabel.setBounds(450, 90, 80, 15);
	outputGainLabel.setBounds(535, 90, 80, 15);
}

//==============================================================================
// This timer periodically checks whether any of the filter's parameters have changed...
void PrototypeAudioProcessorEditor::timerCallback() {
	inputGainSlider.setValue(getProcessor().inputGain->getValue(), dontSendNotification);
	outputGainSlider.setValue(getProcessor().outputGain->getValue(), dontSendNotification);
	subPreGainSlider.setValue(getProcessor().subPreGain->getValue(), dontSendNotification);
	bpFreqSlider.setValue(getProcessor().bpFreq->getValue(), dontSendNotification);
	bpQSlider.setValue(getProcessor().bpQ->getValue(), dontSendNotification);
	masterBypassButton.setToggleState((bool)getProcessor().masterBypass->getValue(), dontSendNotification);
	soloSubButton.setToggleState((bool)getProcessor().soloSub->getValue(), dontSendNotification);
	hystSlider.setValue(getProcessor().hyst->getValue(), dontSendNotification);
	colourSlider.setValue(getProcessor().colour->getValue(), dontSendNotification);
}

//==============================================================================
// This is our Slider::Listener callback, when the user drags a slider.
void PrototypeAudioProcessorEditor::sliderValueChanged(Slider *slider) {
	//getProcessor().inputGain = inputGainSlider.getValue();
	//getProcessor().outputGain = outputGainSlider.getValue();

	if (AudioProcessorParameter* param = getParameterFromSlider(slider))
	{
		// It's vital to use setValueNotifyingHost to change any parameters that are automatable
		// by the host, rather than just modifying them directly, otherwise the host won't know
		// that they've changed.
		param->setValueNotifyingHost((float)slider->getValue());
	}
}

void PrototypeAudioProcessorEditor::sliderDragStarted(Slider* slider)
{
	if (AudioProcessorParameter* param = getParameterFromSlider(slider))
	{
		param->beginChangeGesture();
	}
}

void PrototypeAudioProcessorEditor::sliderDragEnded(Slider* slider)
{
	if (AudioProcessorParameter* param = getParameterFromSlider(slider)) {
		param->endChangeGesture();
	}
}

//==============================================================================
// TODO:: make to toggleButtonClicked?
void PrototypeAudioProcessorEditor::buttonClicked(Button* button)
{
	if (AudioProcessorParameter* param = getParameterFromButton(button)) {
		param->setValueNotifyingHost((float)button->getToggleState());
	}
	
}


//==============================================================================
AudioProcessorParameter* PrototypeAudioProcessorEditor::getParameterFromSlider(const Slider* slider) const {
	if (slider == &inputGainSlider) { return getProcessor().inputGain; }
	if (slider == &outputGainSlider) { return getProcessor().outputGain; }
	if (slider == &subPreGainSlider) { return getProcessor().subPreGain; }
	if (slider == &bpFreqSlider) { return getProcessor().bpFreq; }
	if (slider == &bpQSlider) { return getProcessor().bpQ; }
	if (slider == &hystSlider) { return getProcessor().hyst; }
	if (slider == &colourSlider) { return getProcessor().colour; }

	return nullptr;
}

AudioProcessorParameter* PrototypeAudioProcessorEditor::getParameterFromButton(const Button* button) const {
	if (button == &masterBypassButton) { return getProcessor().masterBypass; }
	if (button == &soloSubButton) { return getProcessor().soloSub; }
}